name:                streaming-http-effectful
version:             0.1.0.0
github:              "deepflowinc-oss/effectful-extras/streaming-http-effectful"
license:             BSD-3-Clause
author:              "DeepFlow, Inc."
maintainer:          "DeepFlow, Inc."
copyright:           "2024 (c) DeepFlow, Inc."

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            A stream-based, simple HTTP client for effectful
category:            Web, Network, Control

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/deepflowinc-oss/effectful-extras/tree/master/streaming-http-effectful#readme>

dependencies:
- base >= 4.7 && < 5

flags:
  attoparsec-aeson:
    manual: false
    default: true
    description: Uses aeson >=2.1 and attoparsec-aeson

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wunused-packages

library:
  source-dirs: src
  when:
  - condition: flag(attoparsec-aeson)
    then:
      dependencies:
      - aeson >= 2.1
      - attoparsec-aeson
    else:
      dependencies:
      - aeson <2.1
  dependencies:
  - attoparsec
  - bytestring
  - effectful
  - effectful-core
  - http-client
  - http-client-tls
  - http-conduit
  - http-types
  - log-effectful
  - random-effectful
  - safe-exceptions
  - streaming-attoparsec
  - streaming-bytestring
  - streaming-http
  - text
