name:                effectful-expiry
version:             0.1.0.0
github:              "deepflowinc/effectful-extras/effectful-expiry"
license:             BSD-3-Clause
author:              "DeepFlow, Inc."
maintainer:          "DeepFlow, Inc."
copyright:           "2024 (c) DeepFlow, Inc."

extra-source-files:
- README.md
- CHANGELOG.md

tested-with:
- GHC == 9.2.8
- GHC == 9.4.8
- GHC == 9.6.4
- GHC == 9.8.2


# Metadata used when publishing your package
synopsis:            Auto-updated resources with expiration time for effectful.
category:            Control, Concurrency, Caching

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/deepflowinc/effectful-extras/tree/master/effectful-expiry#readme>

dependencies:
- base >= 4.7 && < 5
- effectful-core
- effectful
- time
- safe-exceptions
- time-effectful
- unliftio

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wunused-packages

library:
  source-dirs: src
