name:                time-effectful
version:             0.1.0.0
github:              "deepflowinc/effectful-extras/time-effectful"
license:             BSD3
author:              "DeepFlow, Inc."
maintainer:          "DeepFlow, Inc."
copyright:           "2024 (c) DeepFlow, Inc."

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Short description of your package
category:            Time, Control, System

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/deepflowinc/effectful-extras/blob/master/time-effectful#readme>

dependencies:
- base >= 4.7 && < 5
- effectful

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wunused-packages

library:
  source-dirs: src
  dependencies:
  - time
