name:                shake-effectful
version:             0.1.0.0
github:              "deepflowinc/effectful-extras/shake-effectful"
license:             BSD-3-Clause
author:              "DeepFlow, Inc."
maintainer:          "DeepFlow, Inc."
copyright:           "2024 (c) DeepFlow, Inc."

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Interop between shake and effectful.
category:            Control, Development, Shake

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/deepflowinc/effectful-extras/tree/master/effectful-lens#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wunused-packages

library:
  source-dirs: src
  dependencies:
  - aeson
  - effectful
  - log-effectful
  - shake
  - typed-process-effectful
